name = "NewickTree"
uuid = "b0a14db8-6308-4ebc-8917-f72cd81f5094"
authors = ["arzwa <arzwa@psb.vib.ugent.be>"]
version = "0.2.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "^1.4"
AbstractTrees = "0.3.1"
